# Add '~/bin' to PATH
export PATH="$HOME/bin:$PATH";

# work with installed dotfiles
export PATHDOTFILES="$HOME/.dotfiles"

# enable virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/projects
source /usr/local/bin/virtualenvwrapper.sh

# load dotfiles from $PATHDOTFILES
for file in $PATHDOTFILES/.{exports,aliases,functions}; do
	[ -r "$file" ] && [ -f "file" ] && source "$file";
done;
unset file;

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# Append to the Bash history file, rather than overwriting it
shopt -s histappend;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

# bash_completion
if [ -f /etc/bash_completion ]; then
        source /etc/bash_completion;
fi;

# XXX: is this not included in /etc/bash_completion ??
# if [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
#       source /usr/local/etc/bash_completion.d/git-completion.bash
# fi;

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;
