#!/bin/bash
# This hook is sourced after a new virtualenv is activated.
pip install ipython

mkdir -p "$PROJECT_HOME"/`basename $VIRTUAL_ENV`
ve_dir="$PROJECT_HOME"/`basename $VIRTUAL_ENV`
cd "$ve_dir"
